# permissions for end users to edit secretwithexpiries.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: secretwithexpiry-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: k8s-secret-expiry-controller
    app.kubernetes.io/part-of: k8s-secret-expiry-controller
    app.kubernetes.io/managed-by: kustomize
  name: secretwithexpiry-editor-role
rules:
- apiGroups:
  - expiry.devops-360.online
  resources:
  - secretwithexpiries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - expiry.devops-360.online
  resources:
  - secretwithexpiries/status
  verbs:
  - get
