apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: event-creator
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: allow-event-creation
subjects:
  - kind: ServiceAccount
    name: controller-manager
    namespace: system
roleRef:
  kind: ClusterRole
  name: event-creator
  apiGroup: rbac.authorization.k8s.io
