name: Docker build, test, push

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
jobs:
  docker-build:
    name: "🔨 Build 'controller' container image of Kube SecretExpiryController"
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: nasrladib/k8s-secret-expiry-controller
    steps:

    - name: 🔍 check input
      run: |
        echo ${{ inputs.tag }}

    - name: ⬇️ Checkout
      uses: actions/checkout@v3

    - name: 🔑 Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: 📦 Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: 📦 Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: 🐳 Cache Docker layers
      uses: actions/cache@v3
      with:
        path: ${{ github.workspace }}/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: 🐳 Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.IMAGE_NAME }}
        tags: |
          type=raw,value=${{ inputs.tag }}
        labels: |
            maintainer=ladibnasr@gmail.com
            org.opencontainers.image.title=k8s-secret-expiry-controller
            org.opencontainers.image.description=Kubernetes SecretExpiryController system
            org.opencontainers.image.vendor=devops-360-online

    - name: 🐳 Building docker image
      id: docker-build
      uses: docker/build-push-action@v3
      with:
        context: .
        tags: ${{ steps.meta.outputs.tags}}
        load: true
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=local,src=${{ github.workspace }}/.buildx-cache
        cache-to: type=local,dest=${{ github.workspace }}/.buildx-cache

    # - name: Test image

    - name: 🐳 Pushing image to registry
      run: |
        docker push ${{ steps.meta.outputs.tags}}
    
    # - name: Provide changelog